import { FamilySync } from './sync.js';
import { validateFamily } from './family-data.js';
import { currentUser, initAuth, renderAuthPage, renderConfirmation, renderAdmin, accountPanel, bindLogout } from './auth.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cats=['Air & Massa Jenis','Warna & Kimia Seru','Udara & Tekanan','Cahaya & Optik','Suara & Getaran','Magnet','Listrik Statis','Tumbuhan & Biologi','Bumi, Cuaca & Lingkungan','Engineering & Fisika'];
const emojis=['💧','🌈','🎈','🔦','🎵','🧲','⚡','🌱','🌦️','🛠️'];
let KEY,db,familySync,syncInfo={state:'loading',message:'Memuat data akun…'},flushJournal=()=>true,hasJournalDraft=()=>false;
async function loadAccountData(){
  KEY=`genius-kids-lab-v1:${currentUser().id}`;
  let legacy;try{legacy=JSON.parse(localStorage.getItem(KEY))}catch{}
  const initial=legacy?.profiles?.length?legacy:{version:1,active:'first',profiles:[{id:'first',name:'Ilmuwan Cilik',age:8,entries:{}}]};
  familySync=new FamilySync({userId:currentUser().id,initial,hasLegacy:!!legacy?.profiles?.length,
    onData:(data,render)=>{db=data;if(render&&ready)route()},onStatus:info=>{syncInfo=info;updateSyncStatus()},canApply:()=>{
      const form=$('#profile-form');
      return !hasJournalDraft()&&(!form||(form.elements.name.value===profile().name&&+form.elements.age.value===profile().age));
    }});
  await familySync.refresh();
}

let exps=[],query='',category='all',status='all',tab='prepare',freshMission=false,installPrompt,timer=null,remaining=300,timerEnd=0,timerMinutes=5,toastTimer,firstRoute=true;
const reduceMotion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone;
const profile=()=>db.profiles.find(p=>p.id===db.active)||db.profiles[0];
const entry=n=>profile().entries[n]||{};
const pad=n=>String(n).padStart(3,'0');
function save(){const ok=familySync?.save(db);if(!ok)notify(syncInfo.message);return !!ok}
function setEntry(n,v,profileId=profile().id){const target=db.profiles.find(p=>p.id===profileId);if(!target)return false;const before=target.entries[n];target.entries[n]={...before,...v,updated:new Date().toISOString()};if(!save()){if(before===undefined)delete target.entries[n];else target.entries[n]=before;return false}return true}

function notify(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}
const done=()=>exps.filter(e=>entry(e.n).done).length;
const current=()=>Number(location.hash.split('/')[1]);
const catIndex=n=>Math.floor((n-1)/10);
const catDone=i=>exps.filter(e=>catIndex(e.n)===i&&entry(e.n).done).length;
const journals=()=>Object.values(profile().entries).filter(e=>e.observation).length;
const icons={home:'<path d="M3 10.5 12 3l9 7.5V20a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',explore:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',journal:'<path d="M5 5a2 2 0 0 1 2-2h12v15H7a2 2 0 0 0-2 2z"/><path d="M5 20a2 2 0 0 0 2 1h12v-3M9 7h6M9 11h4"/>',badges:'<circle cx="12" cy="9" r="6"/><path d="m8.5 14-1.5 7 5-3 5 3-1.5-7"/>',parent:'<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20a6.5 6.5 0 0 1 13 0"/><circle cx="17.5" cy="9.5" r="2.5"/><path d="M16 14.2a5 5 0 0 1 5.5 4.8"/>'};
const icon=n=>`<svg class="ico" viewBox="0 0 24 24" aria-hidden="true">${icons[n]}</svg>`;
const titles={home:'Ruang eksplorasi',explore:'100 misi sains',journal:'Jurnal penemuan',badges:'Pencapaian',parent:'Area orang tua'};
function shell(content,active='home',title){const p=profile(),initial=esc(p.name.slice(0,1).toUpperCase());document.title=`${title||titles[active]} · Genius Kids Lab`;$('#app').innerHTML=`<button class="skip" id="skip">Lewati ke konten</button><aside><a class="brand" href="#home"><img src="/assets/logo.png" alt="Genius Kids"><span>LAB<span class="branddot">•</span></span></a><div class="workspace-label">LABORATORIUM KECILMU</div><nav class="side-nav" aria-label="Menu utama">${[['home','Beranda','Beranda'],['explore','Jelajah misi','Misi'],['journal','Jurnal penemuan','Jurnal'],['badges','Lencana','Lencana'],['parent','Area orang tua','Orang tua']].map(([id,name,short])=>`<a href="#${id}" class="${active===id?'active':''}" ${active===id?'aria-current="page"':''}>${icon(id)}<span class="long">${name}</span><span class="short">${short}</span></a>`).join('')}</nav><div class="aside-bottom"><div class="mini-orbit">✧</div><strong>Rasa ingin tahu<br>membawa kita jauh.</strong><p>Satu pertanyaan.<br>Satu penemuan baru.</p>${standalone()?'':'<button id="install" class="small ghost">＋ Pasang aplikasi</button>'}</div><a class="profile-link" href="#parent"><span class="avatar">${initial}</span><div><b>${esc(p.name)}</b><small>${p.age} tahun · ganti profil</small></div><span aria-hidden="true">›</span></a></aside><div class="main-shell"><header><a href="#home" class="mobile-brand"><img src="/assets/logo.png" alt=""><span>Genius Kids <b>Lab</b></span></a><span class="breadcrumb">Genius Kids / <b>${esc(title||titles[active]||'Misi sains')}</b></span><div class="header-actions"><button type="button" id="sync-status" class="sync-status" aria-label="Statistik sinkronisasi"></button>${currentUser()?.role==='admin'?'<a class="admin-nav-link" href="#admin">Admin</a>':''}<a href="#badges" class="header-progress" aria-label="${done()} dari 100 misi selesai"><span class="header-bar" aria-hidden="true"><i style="width:${done()}%"></i></span>✦ ${done()} / 100</a><a href="#parent" class="avatar header-avatar" aria-label="Profil ${esc(p.name)}">${initial}</a></div></header><main id="main">${content}</main><footer>Genius Kids Lab · Belajar dengan mencoba <span>Profil & jurnal tersimpan per akun</span></footer></div>`;if($('#install'))$('#install').onclick=install;$('#skip').onclick=focusMain;updateSyncStatus();$('#sync-status').onclick=showSync}
function focusMain(){const h=$('#main h1')||$('#main h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}
function card(e){const i=catIndex(e.n),r=entry(e.n);return `<a class="mission-card ${r.done?'is-done':r.started?'is-started':''}" href="#mission/${e.n}"><div class="card-art cat-${i}"><span class="exp-number">MISI ${pad(e.n)}</span><span class="art-emoji" aria-hidden="true">${emojis[i]}</span><span class="card-status">${r.done?'✓ Selesai':r.started?'● Sedang dicoba':'Ayo coba'}</span></div><div class="card-body"><small>${esc(cats[i])}</small><h3>${esc(e.title)}</h3><div class="card-meta"><span>◷ ${esc(e.minutes)}</span><span>${esc(e.age)} th</span>${e.level==='Dengan pendamping'?'<span class="meta-adult">👪 Pendamping</span>':`<span>${esc(e.level)}</span>`}</div></div></a>`}
function home(){const p=profile(),next=exps.find(e=>entry(e.n).started&&!entry(e.n).done)||exps.find(e=>!entry(e.n).done)||exps[0],resume=entry(next.n).started&&!entry(next.n).done,badgeCount=cats.filter((_,i)=>catDone(i)===10).length;
shell(`<div class="page-heading"><div><p class="eyebrow">SELAMAT DATANG DI LAB</p><h1>Halo, ${esc(p.name)}! <span aria-hidden="true">👋</span></h1><p>Penemuan apa yang akan kamu buat hari ini?</p></div><a class="button secondary" href="#parent">Profil keluarga</a></div><section class="hero"><div class="hero-copy"><span class="pill">✦ 10 dunia · 100 penemuan</span><h2>Ide kecil.<br>Penemuan <em>besar.</em></h2><p>Siapkan rasa ingin tahumu. Pilih misi, coba bersama, dan ceritakan penemuanmu.</p><a class="button white" href="#mission/${next.n}">${resume?'Lanjutkan misi':done()?'Misi berikutnya':'Mulai petualangan'} <span aria-hidden="true">→</span></a><p class="hero-next">Misi ${pad(next.n)} · ${esc(next.title)}</p></div><img src="/assets/workshop.webp" alt="Anak merancang menara dan jembatan kertas" class="hero-image"><div class="hero-sticker" aria-hidden="true">COBA · AMATI<br><b>TEMUKAN!</b></div></section><section class="stats" aria-label="Ringkasan progres"><a href="#explore"><span class="stat-icon blue" aria-hidden="true">✓</span><div><strong>${done()} <small>/ 100</small></strong><p>Misi selesai</p></div></a><a href="#journal"><span class="stat-icon yellow" aria-hidden="true">✎</span><div><strong>${journals()}</strong><p>Catatan penemuan</p></div></a><a href="#badges"><span class="stat-icon pink" aria-hidden="true">✦</span><div><strong>${badgeCount} <small>/ 10</small></strong><p>Lencana kategori</p></div></a></section><div class="section-head"><div><p class="eyebrow">PILIH DUNIAMU</p><h2>Rasa penasaran dimulai di sini</h2></div><a href="#explore">Lihat semua <span aria-hidden="true">→</span></a></div><div class="category-strip">${cats.map((c,i)=>{const n=catDone(i);return `<button data-cat="${i}" class="category-tile cat-${i} ${n===10?'complete':''}"><span class="tile-emoji" aria-hidden="true">${emojis[i]}</span><b>${esc(c)}</b><small>${n?`${n}/10 selesai`:'10 misi'}</small><span class="tile-bar" aria-hidden="true"><i style="width:${n*10}%"></i></span></button>`}).join('')}</div><div class="section-head"><h2>Siap dicoba hari ini</h2><span class="muted">Bahan sederhana, ide luar biasa</span></div><div class="cards">${[next,...exps.filter(e=>[11,91].includes(e.n)&&e.n!==next.n)].slice(0,3).map(card).join('')}</div>`);
$$('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;status='all';query='';location.hash='explore'})}
function explore(){shell(`<div class="page-heading"><div><p class="eyebrow">100 MISI SAINS</p><h1>Jelajah rasa ingin tahu</h1><p>Cari berdasarkan nama, konsep, atau bahan yang tersedia.</p></div></div><div class="filters"><label class="search"><span aria-hidden="true">${icon('explore')}</span><input id="search" type="search" placeholder="Coba: balon, air, kertas…" value="${esc(query)}" aria-label="Cari eksperimen" autocomplete="off"></label><select id="status" aria-label="Status"><option value="all">Semua progres</option><option value="new" ${status==='new'?'selected':''}>Belum selesai</option><option value="done" ${status==='done'?'selected':''}>Selesai</option></select></div><div class="chips" role="group" aria-label="Kategori"><button class="chip" data-chip="all" aria-pressed="${category==='all'}">Semua</button>${cats.map((c,i)=>`<button class="chip" data-chip="${i}" aria-pressed="${String(i)===category}"><span aria-hidden="true">${emojis[i]}</span>${esc(c)}</button>`).join('')}</div><p id="count" class="muted count" aria-live="polite"></p><div id="results" class="cards"></div>`,'explore');
function reset(){query='';category='all';status='all';explore()}
function results(){const q=query.trim().toLowerCase(),list=exps.filter(e=>(category==='all'||String(catIndex(e.n))===category)&&(status==='all'||(status==='done'?entry(e.n).done:!entry(e.n).done))&&`${e.title} ${e.concept} ${e.materials.join(' ')}`.toLowerCase().includes(q)),filtered=q||category!=='all'||status!=='all';$('#count').innerHTML=`<b>${list.length}</b> misi untuk dijelajahi${filtered?' <button class="link" id="reset">Hapus filter</button>':''}`;$('#results').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><span aria-hidden="true">🔍</span><h2>Belum ketemu?</h2><p>Coba kata bahan lain atau lihat semua kategori.</p><button class="button" id="reset-empty">Tampilkan semua misi</button></div>`;for(const id of ['#reset','#reset-empty'])if($(id))$(id).onclick=reset}
$('#search').oninput=e=>{query=e.target.value;results()};$('#status').onchange=e=>{status=e.target.value;results()};
$$('[data-chip]').forEach(b=>b.onclick=()=>{category=b.dataset.chip;$$('[data-chip]').forEach(x=>x.setAttribute('aria-pressed',x===b));results()});
const sel=$('[data-chip][aria-pressed="true"]');if(sel&&category!=='all')sel.scrollIntoView({block:'nearest',inline:'center'});results()}
function goTab(id,focus){if(!flushJournal())return;flushJournal=()=>true;hasJournalDraft=()=>false;tab=id;mission();const t=$('.tabs');if(t&&t.getBoundingClientRect().top<0)t.scrollIntoView({behavior:reduceMotion()?'auto':'smooth',block:'start'});if(focus)$(`#tab-${id}`).focus()}
function mission(){const e=exps.find(x=>x.n===current());if(!e){shell('<div class="empty"><span aria-hidden="true">🧭</span><h1>Misi tidak ditemukan</h1><a class="button" href="#explore">Kembali ke katalog</a></div>','explore');return}
let r=entry(e.n);const i=catIndex(e.n),ids=['prepare','steps','learn','journal'];
if(freshMission){freshMission=false;const h=location.hash.split('/')[2];tab=ids.includes(h)?h:r.done?'journal':r.started?'steps':'prepare'}
if(tab==='learn'&&r.started&&!r.learned){setEntry(e.n,{learned:true});r=entry(e.n)}
const tabs=[['prepare','Siapkan',r.safe],['steps','Coba',(r.steps||[]).length>=e.steps.length],['learn','Pahami',r.learned],['journal','Catat',r.done]],prev=exps.find(x=>x.n===e.n-1),next=exps.find(x=>x.n===e.n+1);
shell(`<a href="#explore" class="back">← Jelajah misi</a><div class="mission-heading"><div><p class="eyebrow">MISI ${pad(e.n)} · ${esc(cats[i])}</p><h1>${esc(e.title)}</h1><p>${esc(e.mission)}</p><div class="tags"><span>${esc(e.age)} tahun</span><span>◷ ${esc(e.minutes)}</span><span>${esc(e.concept)}</span><span class="${e.level==='Dengan pendamping'?'tag-adult':''}">${e.level==='Dengan pendamping'?'👪 ':''}${esc(e.level)}</span>${r.done?'<span class="tag-done">✓ Selesai</span>':''}</div></div><div class="mission-emblem cat-${i}" aria-hidden="true">${emojis[i]}</div></div>${e.n===85?'<div class="danger" role="alert"><strong>Air hasil eksperimen tidak boleh diminum.</strong><p>Air yang jernih belum tentu bebas kuman atau zat terlarut.</p></div>':''}<div class="tabs" role="tablist" aria-label="Tahap misi">${tabs.map(([id,name,ok],j)=>`<button role="tab" id="tab-${id}" aria-controls="mission-content" aria-selected="${tab===id}" tabindex="${tab===id?0:-1}" class="${tab===id?'selected':''} ${ok?'ok':''}" data-tab="${id}"><span class="tab-num" aria-hidden="true">${ok?'✓':j+1}</span>${name}${ok?'<span class="sr-only"> (sudah)</span>':''}</button>`).join('')}</div><div id="mission-content" role="tabpanel" aria-labelledby="tab-${tab}"></div><nav class="mission-pager" aria-label="Misi lain">${prev?`<a href="#mission/${prev.n}"><small>← Misi ${pad(prev.n)}</small><span>${esc(prev.title)}</span></a>`:'<span></span>'}${next?`<a href="#mission/${next.n}" class="next"><small>Misi ${pad(next.n)} →</small><span>${esc(next.title)}</span></a>`:''}</nav>`,'explore',e.title);
$$('[data-tab]').forEach(b=>{b.onclick=()=>goTab(b.dataset.tab);b.onkeydown=x=>{const k={ArrowRight:1,ArrowLeft:-1}[x.key];if(k){x.preventDefault();goTab(ids[(ids.indexOf(b.dataset.tab)+k+4)%4],true)}else if(x.key==='Home'||x.key==='End'){x.preventDefault();goTab(x.key==='Home'?ids[0]:ids[3],true)}}});
const panel=$('#mission-content');
if(tab==='prepare'){const mats=()=>`${$$('[data-material]:checked').length}/${e.materials.length} bahan siap`;panel.innerHTML=`<div class="two-col"><section class="panel"><div class="panel-head"><h2>Siapkan bahanmu</h2><span class="count-pill" id="mat-count">${(r.materials||[]).length}/${e.materials.length} bahan siap</span></div><p class="muted">Centang yang sudah tersedia.</p><div class="checklist">${e.materials.map((m,j)=>`<label><input type="checkbox" data-material="${j}" ${(r.materials||[]).includes(j)?'checked':''}><span>${esc(m)}</span></label>`).join('')}</div></section><section class="panel tint"><span class="eyebrow">BERSAMA PENDAMPING</span><h2>Aman dulu, ya! <span aria-hidden="true">🦺</span></h2><p>${esc(e.safety)}</p><hr><h3>Sebelum mulai</h3><p>${esc(e.prep)}</p><label class="checkline safe-check"><input id="safe" type="checkbox" ${r.safe?'checked':''}><span>Kami sudah membaca petunjuk keamanan bersama.</span></label><button class="button big" id="start">Siap, mulai misi <span aria-hidden="true">→</span></button></section></div>`;
$$('[data-material]').forEach(b=>b.onchange=()=>{setEntry(e.n,{materials:$$('[data-material]:checked').map(x=>+x.dataset.material)});$('#mat-count').textContent=mats()});$('#safe').onchange=x=>{setEntry(e.n,{safe:x.target.checked});$('.safe-check').classList.remove('attention')};
$('#start').onclick=()=>{if(!entry(e.n).safe){notify('Baca petunjuk keamanan bersama pendamping terlebih dahulu.');const c=$('.safe-check');c.classList.remove('attention');void c.offsetWidth;c.classList.add('attention');$('#safe').focus();return}setEntry(e.n,{started:true});goTab('steps')}}
if(tab==='steps'){const n=(r.steps||[]).length,len=e.steps.length;panel.innerHTML=`<div class="two-col"><section class="panel"><div class="panel-head"><h2>Satu langkah, satu penemuan</h2><span class="count-pill" id="step-count">${n}/${len} langkah</span></div><progress id="step-progress" max="${len}" value="${n}" aria-label="Langkah selesai"></progress>${e.steps.map((s,j)=>`<label class="step"><input type="checkbox" data-step="${j}" ${(r.steps||[]).includes(j)?'checked':''}><b aria-hidden="true">${j+1}</b><span>${esc(s)}</span></label>`).join('')}<button class="button big" id="to-learn">Cari tahu mengapa <span aria-hidden="true">→</span></button></section><div><section class="panel timer"><p class="eyebrow">TIMER BANTU</p><div id="clock" class="${timer?'running':''}" role="timer" aria-live="off">${formatTime(remaining)}</div><label>Durasi (menit)<input id="minutes" type="number" inputmode="numeric" min="1" max="180" value="${timerMinutes}"></label><div class="timer-actions"><button id="timer-toggle" class="button">${timer?'⏸ Jeda':'▶ Mulai'}</button><button id="timer-reset" class="button secondary">Atur ulang</button></div><small>Untuk jeda pengamatan singkat. Tetap ikuti durasi pada panduan.</small></section><section class="panel tint"><h3>Belum berhasil? <span aria-hidden="true">🤔</span></h3><p>${esc(e.troubleshoot)}</p></section></div></div>`;
$$('[data-step]').forEach(b=>b.onchange=()=>{const list=$$('[data-step]:checked').map(x=>+x.dataset.step);setEntry(e.n,{steps:list,started:true});$('#step-count').textContent=`${list.length}/${len} langkah`;$('#step-progress').value=list.length;if(list.length===len)notify('Semua langkah selesai! Ayo cari tahu mengapa.')});$('#to-learn').onclick=()=>goTab('learn');
const setMinutes=()=>{timerMinutes=Math.max(1,Math.min(180,Math.round(Number($('#minutes').value))||5));remaining=timerMinutes*60;$('#clock').textContent=formatTime(remaining)};
$('#minutes').onchange=()=>{if(!timer)setMinutes()};
$('#timer-toggle').onclick=()=>{if(timer){remaining=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));clearInterval(timer);timer=null}else{if(!remaining)setMinutes();timerEnd=Date.now()+remaining*1000;timer=setInterval(tick,250)}$('#timer-toggle').textContent=timer?'⏸ Jeda':'▶ Mulai';$('#clock').classList.toggle('running',!!timer)};
$('#timer-reset').onclick=()=>{clearInterval(timer);timer=null;setMinutes();$('#timer-toggle').textContent='▶ Mulai';$('#clock').classList.remove('running')}}
if(tab==='learn'){panel.innerHTML=`<div class="two-col"><section class="panel"><p class="eyebrow">KENAPA BISA BEGITU?</p>${e.science.map(([t,b],j)=>`<div class="science-row"><span aria-hidden="true">${j+1}</span><div><h3>${esc(t)}</h3><p>${esc(b)}</p></div></div>`).join('')}<div class="note"><b>Di sekitarmu <span aria-hidden="true">🏠</span></b><p>${esc(e.everyday)}</p></div></section><section class="panel tint"><h2>Amati hasilmu</h2><p>${esc(e.observed)}</p><h3>Hasil berbeda juga berarti</h3><p>${esc(e.variation)}</p><details><summary>${esc(e.parent_q)}</summary><p>${esc(e.parent_a)}</p></details><button class="button big" id="to-journal">Tulis penemuanku <span aria-hidden="true">→</span></button></section></div>`;$('#to-journal').onclick=()=>goTab('journal')}
if(tab==='journal'){const trials=e.trials||[];panel.innerHTML=`<div class="two-col"><form class="panel" id="journal-form"><div class="panel-head"><h2>Jurnal penemuanku</h2><span class="save-state" id="save-state" aria-live="polite"></span></div><label>Dugaan atau ide awal<textarea name="prediction" placeholder="${esc(e.journal_prompt)}">${esc(r.prediction||'')}</textarea></label><label>Apa yang kamu lihat?<textarea name="observation" placeholder="${esc(e.journal_observe)}">${esc(r.observation||'')}</textarea></label><label>Hasil ukur (jumlah, cm, detik, atau lainnya)<input name="measurement" value="${esc(r.measurement||'')}" placeholder="Contoh: jembatan menahan 8 koin"></label><label>Satu hal yang ingin kuubah<textarea name="revision" placeholder="Aku akan mengubah... karena...">${esc(r.revision||'')}</textarea></label><div class="field"><p class="field-label">Foto percobaan <span class="muted">(opsional, maks. 5 MB)</span></p><div id="photo-preview">${r.photo?`<img class="journal-photo" src="${r.photo}" alt="Foto percobaan"><button type="button" id="remove-photo" class="small ghost">Hapus foto</button>`:`<label class="file-button"><input id="photo" type="file" accept="image/jpeg,image/png,image/webp" class="sr-only"><span aria-hidden="true">📷</span> Tambah foto</label>`}</div></div><div class="form-actions"><button type="button" id="complete" class="button big ${r.done?'is-done':''}">${r.done?'✓ Misi selesai':'Tandai misi selesai 🎉'}</button><button class="button secondary" type="submit">Simpan jurnal</button></div><small>Jurnal disimpan di perangkat lalu disinkronkan saat online. Isi pengamatan sebelum menyelesaikan misi.</small></form><section class="panel tint"><p class="eyebrow">COBA VERSI KEDUA</p><h2>${esc(e.challenge)}</h2><ol>${e.challenge_steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="note"><strong>Uji yang adil</strong><p>${esc(e.variable)}</p></div>${trials.length?`<h3>Tabel percobaan</h3><div class="trials" id="trials">${trials.map((t,j)=>`<label><span>${esc(t)}</span><input data-trial="${j}" value="${esc((r.trials||[])[j]||'')}" placeholder="Hasilnya…" aria-label="Hasil untuk ${esc(t)}"></label>`).join('')}</div>`:''}<h3>Bandingkan percobaan</h3><p>Ceritakan hasil awal dan hasil setelah kamu mengubah satu hal.</p></section></div>`;
const form=$('#journal-form'),profileId=profile().id,trialInputs=$$('[data-trial]');let saveT,dirty=false;
function persist(){const v=Object.fromEntries(new FormData(form));if(trialInputs.length)v.trials=trialInputs.map(x=>x.value.slice(0,200));const ok=setEntry(e.n,{...v,started:true},profileId);if(ok)dirty=false;return ok}
function flush(){clearTimeout(saveT);return !dirty||persist()}flushJournal=flush;hasJournalDraft=()=>dirty;
function queue(){dirty=true;clearTimeout(saveT);$('#save-state').textContent='Menyimpan…';saveT=setTimeout(()=>{if(persist()&&$('#save-state'))$('#save-state').textContent='✓ Tersimpan'},700)}
form.oninput=x=>{x.target.classList.remove('invalid');if(x.target.id!=='photo')queue()};if($('#trials'))$('#trials').oninput=queue;
form.onsubmit=x=>{x.preventDefault();clearTimeout(saveT);if(persist()){$('#save-state').textContent='✓ Tersimpan';notify('Penemuanmu berhasil disimpan!')}};
$('#complete').onclick=()=>{const obs=form.elements.namedItem('observation');if(!obs.value.trim()){obs.focus();obs.classList.add('invalid');notify('Ceritakan apa yang kamu amati dulu, ya.');return}clearTimeout(saveT);if(!entry(e.n).safe){persist();tab='prepare';mission();notify('Konfirmasi petunjuk keamanan bersama pendamping dahulu.');return}const was=r.done;if(persist()&&setEntry(e.n,{done:true,completedAt:r.completedAt||new Date().toISOString()})){mission();if(!was)celebrate(e);else notify('Jurnal misi diperbarui.')}};
if($('#photo'))$('#photo').onchange=async x=>{const f=x.target.files[0];if(!f)return;if(f.size>5*1024*1024){notify('Pilih foto maksimal 5 MB.');return}try{const img=await createImageBitmap(f);if(!form.isConnected){img.close();return}const can=document.createElement('canvas'),s=Math.min(1,900/img.width,900/img.height);can.width=img.width*s;can.height=img.height*s;can.getContext('2d').drawImage(img,0,0,can.width,can.height);clearTimeout(saveT);if(persist()&&setEntry(e.n,{photo:can.toDataURL('image/jpeg',.65)},profileId)){mission();notify('Foto tersimpan.')}}catch{notify('Foto tidak dapat dibuka. Pilih JPG atau PNG.')}};
if($('#remove-photo'))$('#remove-photo').onclick=()=>{if(!confirm('Hapus foto percobaan ini?'))return;clearTimeout(saveT);persist();setEntry(e.n,{photo:null});mission()}}
}
function celebrate(e){const i=catIndex(e.n),badge=catDone(i)===10,next=exps.find(x=>x.n>e.n&&!entry(x.n).done)||exps.find(x=>!entry(x.n).done),d=document.createElement('dialog');d.className='celebrate';d.setAttribute('aria-labelledby','celebrate-title');
d.innerHTML=`<div class="confetti" aria-hidden="true">${Array.from({length:18},(_,j)=>`<i style="--x:${(j*37)%100}%;--d:${(j%6)*.12}s;--c:${['#ffcb47','#1462df','#e35c80','#2bb673','#8a63e8'][j%5]}"></i>`).join('')}</div><div class="celebrate-emoji" aria-hidden="true">${badge?emojis[i]:'🎉'}</div><p class="eyebrow">${badge?'LENCANA BARU':'MISI '+pad(e.n)+' SELESAI'}</p><h2 id="celebrate-title">${badge?`Lencana ${esc(cats[i])} terbuka!`:`Hebat, ${esc(profile().name)}!`}</h2><p>${badge?'Kamu menyelesaikan 10 misi di dunia ini. Sertifikatmu siap dicetak.':`Satu penemuan baru tersimpan. Sudah ${done()} dari 100 misi.`}</p><div class="form-actions">${badge?'<a class="button" href="#badges">Lihat lencana</a>':next?`<a class="button" href="#mission/${next.n}">Misi berikutnya →</a>`:''}<a class="button secondary" href="#journal">Lihat jurnal</a><button class="button ghost" data-close>Tutup</button></div>`;
document.body.append(d);d.addEventListener('close',()=>d.remove());d.onclick=x=>{if(x.target===d||x.target.closest('a,[data-close]'))d.close()};d.showModal();navigator.vibrate?.(80)}
function formatTime(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function tick(){remaining=Math.max(0,Math.ceil((timerEnd-Date.now())/1000));if($('#clock'))$('#clock').textContent=formatTime(remaining);if(!remaining){clearInterval(timer);timer=null;if($('#timer-toggle'))$('#timer-toggle').textContent='▶ Mulai';$('#clock')?.classList.remove('running');navigator.vibrate?.([200,100,200]);notify('⏰ Waktu pengamatan selesai. Lihat dan catat hasilmu!')}}
function journal(){const list=exps.filter(e=>entry(e.n).observation).sort((a,b)=>String(entry(b.n).updated||'').localeCompare(entry(a.n).updated||''));shell(`<div class="page-heading"><div><p class="eyebrow">CERITA DARI LABMU</p><h1>Jurnal penemuan</h1><p>${list.length?`${list.length} cerita kecil tentang hal-hal yang kamu temukan.`:'Cerita penemuanmu akan muncul di sini.'}</p></div>${list.length?'<button class="button secondary" id="print">Cetak jurnal</button>':''}</div><div class="journal-grid">${list.length?list.map(e=>{const r=entry(e.n),i=catIndex(e.n);return `<article class="panel journal-item">${r.photo?`<img src="${r.photo}" class="journal-photo" alt="Foto percobaan ${esc(e.title)}">`:''}<div class="journal-meta"><span class="journal-emoji cat-${i}" aria-hidden="true">${emojis[i]}</span><small>MISI ${pad(e.n)} · ${new Date(r.updated).toLocaleDateString('id-ID',{dateStyle:'medium'})}</small>${r.done?'<span class="tag-done">✓ Selesai</span>':''}</div><h2>${esc(e.title)}</h2>${r.prediction?`<p class="journal-pred"><b>Dugaanku:</b> ${esc(r.prediction)}</p>`:''}<p>${esc(r.observation)}</p>${r.measurement?`<div class="note"><b>Hasil ukur:</b> ${esc(r.measurement)}</div>`:''}${r.revision?`<p><b>Ide berikutnya:</b> ${esc(r.revision)}</p>`:''}<a href="#mission/${e.n}/journal">Lihat & edit →</a></article>`}).join(''):'<div class="empty"><span aria-hidden="true">📒</span><h2>Halaman pertama menantimu</h2><p>Selesaikan pengamatan pertamamu dan simpan ceritanya.</p><a class="button" href="#explore">Pilih misi</a></div>'}</div>`,'journal');if($('#print'))$('#print').onclick=()=>window.print()}
function badges(){const d=done(),next=cats.map((c,i)=>[i,catDone(i)]).filter(([,n])=>n<10).sort((a,b)=>b[1]-a[1])[0];shell(`<div class="page-heading"><div><p class="eyebrow">JEJAK PETUALANGANMU</p><h1>Setiap usaha berarti</h1><p>Selesaikan 10 misi dalam satu kategori untuk mendapat lencananya.</p></div></div><section class="progress-banner"><div><h2>${d} penemuan sudah dicatat</h2><p>${!d?'Selesaikan misi pertamamu untuk memulai perjalanan.':next?`Paling dekat: <b>${esc(cats[next[0]])}</b> — tinggal ${10-next[1]} misi lagi!`:'Luar biasa! Semua lencana sudah terbuka.'}</p></div><div class="ring" style="--p:${d}" role="img" aria-label="${d} dari 100 misi"><span>${d}%</span></div></section><div class="badge-grid">${cats.map((c,i)=>{const n=catDone(i);return `<section class="panel badge ${n===10?'unlocked':''}"><span class="badge-medal cat-${i}" aria-hidden="true">${emojis[i]}${n<10?'<i>🔒</i>':''}</span><h3>${esc(c)}</h3><p>${n}/10 misi ${n===10?'· Lencana terbuka!':''}</p><progress max="10" value="${n}" aria-label="Progres ${esc(c)}"></progress>${n===10?`<button class="button secondary" data-certificate="${i}">Cetak sertifikat</button>`:`<button class="link" data-cat="${i}">${n?'Lanjutkan':'Lihat misinya'} →</button>`}</section>`}).join('')}</div>`,'badges');$$('[data-certificate]').forEach(b=>b.onclick=()=>certificate(+b.dataset.certificate));$$('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;status='all';query='';location.hash='explore'})}
function certificate(i){shell(`<section class="certificate"><img src="/assets/logo.png" alt="Genius Kids"><p>SERTIFIKAT PENJELAJAH SAINS</p><h1>${esc(profile().name)}</h1><p>Telah menyelesaikan 10 misi</p><h2>${esc(cats[i])}</h2><p>Berani bertanya, mencoba, dan menceritakan penemuan.</p><div class="seal">${emojis[i]}</div><p>${new Date().toLocaleDateString('id-ID',{dateStyle:'long'})}</p><button class="button no-print" onclick="window.print()">Cetak / simpan PDF</button><a class="no-print" href="#badges">Kembali ke lencana</a></section>`,'badges','Sertifikat');window.scrollTo(0,0)}
function download(name,data){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function parent(){const p=profile();shell(`${accountPanel()}<div class="page-heading"><div><p class="eyebrow">BELAJAR BERSAMA KELUARGA</p><h1>Area orang tua</h1><p>Kelola profil, dampingi eksperimen, dan simpan cerita anak.</p></div></div><div class="two-col"><section class="panel"><h2>Profil penjelajah</h2><p class="field-label">Siapa yang sedang bereksperimen?</p><div class="profile-chips">${db.profiles.map(x=>`<button type="button" class="profile-chip" data-profile="${esc(x.id)}" aria-pressed="${x.id===p.id}"><span class="avatar">${esc(x.name.slice(0,1).toUpperCase())}</span>${esc(x.name)}</button>`).join('')}${db.profiles.length<5?'<button type="button" id="add-profile" class="profile-chip add">＋ Tambah anak</button>':''}</div><form id="profile-form"><label>Nama panggilan<input name="name" maxlength="35" required value="${esc(p.name)}" autocomplete="off"></label><label>Usia<input name="age" type="number" inputmode="numeric" min="4" max="17" required value="${p.age}"></label><div class="form-actions"><button class="button">Simpan profil</button>${db.profiles.length>1?'<button id="delete-profile" type="button" class="button danger-ghost">Hapus profil</button>':''}</div></form><hr><h3>Ringkasan ${esc(p.name)}</h3><div class="summary"><div><strong>${done()}</strong><span>misi selesai</span></div><div><strong>${journals()}</strong><span>jurnal</span></div><div><strong>${cats.filter((_,i)=>catDone(i)===10).length}</strong><span>lencana</span></div></div><div class="note"><b>Tips mendampingi</b><p>Awali dengan pertanyaan: “Menurutmu apa yang akan terjadi?” Setelah uji, minta anak menjelaskan apa yang berubah.</p></div></section><section class="panel tint"><h2>Jaga penemuan tetap tersimpan</h2><p>Profil, progres, jurnal, dan foto tersinkron ke akun saat online. Lihat status sinkronisasi sebelum berpindah perangkat. Ekspor tetap tersedia sebagai cadangan.</p><div class="form-actions"><button class="button" id="export">↓ Ekspor semua jurnal</button><label class="file-button"><input id="import" type="file" accept="application/json,.json" class="sr-only">↑ Pulihkan cadangan</label></div><small>Pemulihan mengganti data akun ini dan akan disinkronkan ke perangkat lain setelah konfirmasi.</small><div id="legacy-backup"></div>${standalone()?'':'<hr><h3>Pasang di layar utama</h3><p>Di Chrome/Edge gunakan tombol pasang. Di Safari iPhone, buka menu Bagikan lalu “Tambahkan ke Layar Utama”.</p><button class="button secondary" id="install-parent">Pasang aplikasi</button>'}<hr><details><summary>Tentang akses dan privasi</summary><p>Akun dan sesi login dikelola Supabase Auth. Profil anak, progres, foto, dan jurnal disimpan privat di Supabase per akun. Salinan lokal dipakai saat offline; data hanya dapat diakses API akun pemiliknya. Materi eksperimen tetap dapat diakses publik. Gunakan ekspor untuk mencadangkan jurnal.</p></details></section></div>`,'parent');
bindLogout(notify,async()=>{if(!flushJournal())return false;const synced=await familySync.flush();return synced||confirm('Ada perubahan yang belum tersinkron. Salinan lokal tetap tersedia di browser ini. Tetap keluar?')});
try{const legacy=JSON.parse(localStorage.getItem('genius-kids-lab-v1'));if(legacy?.profiles?.length){$('#legacy-backup').innerHTML='<hr><h3>Cadangan versi lama</h3><p>Data sebelum fitur akun masih tersedia di browser ini. Unduh lalu pulihkan jika data tersebut milik keluarga Anda.</p><button class="button secondary" id="export-legacy">Unduh cadangan versi lama</button>';$('#export-legacy').onclick=()=>download('genius-kids-cadangan-versi-lama.json',legacy)}}catch{}
$$('[data-profile]').forEach(b=>b.onclick=()=>{const previous=db.active;db.active=b.dataset.profile;if(!save()){db.active=previous;return}parent();notify(`Profil ${profile().name} aktif`)});
$('#profile-form').onsubmit=e=>{e.preventDefault();const oldName=p.name,oldAge=p.age;p.name=e.target.elements.namedItem('name').value.trim()||'Ilmuwan Cilik';p.age=+e.target.elements.namedItem('age').value;if(!save()){p.name=oldName;p.age=oldAge;return}parent();notify('Profil tersimpan')};
if($('#add-profile'))$('#add-profile').onclick=()=>{const x={id:crypto.randomUUID(),name:'Penjelajah Baru',age:8,entries:{}};const previous=db.active;db.profiles.push(x);db.active=x.id;if(!save()){db.profiles.pop();db.active=previous;return}parent();const n=$('#profile-form input');n.focus();n.select()};
if($('#delete-profile'))$('#delete-profile').onclick=()=>{if(!confirm(`Hapus profil ${p.name} beserta semua jurnal dan fotonya? Tindakan ini tidak dapat dibatalkan.`))return;const previous=db.profiles;db.profiles=db.profiles.filter(x=>x.id!==p.id);db.active=db.profiles[0].id;if(!save()){db.profiles=previous;db.active=p.id;return}parent();notify('Profil dihapus')};
$('#export').onclick=()=>{download(`genius-kids-cadangan-${new Date().toISOString().slice(0,10)}.json`,db);notify('Cadangan diunduh')};if($('#install-parent'))$('#install-parent').onclick=install;
$('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>15*1024*1024)throw Error();const v=JSON.parse(await f.text());validateFamily(v);if(v.version!==1||!Array.isArray(v.profiles)||!v.profiles.length||v.profiles.length>5)throw Error();for(const p of v.profiles){if(typeof p.id!=='string'||typeof p.name!=='string'||p.name.length>35||!Number.isInteger(p.age)||p.age<4||p.age>17||!p.entries||typeof p.entries!=='object')throw Error();for(const [n,r] of Object.entries(p.entries)){if(!exps.some(e=>e.n===+n)||!r||typeof r!=='object')throw Error();if(r.photo&&!/^data:image\/(jpeg|png|webp);base64,[a-zA-Z0-9+/=]+$/.test(r.photo))throw Error();for(const k of ['prediction','observation','revision','measurement'])if(r[k]!=null&&typeof r[k]!=='string')throw Error();for(const k of ['materials','steps'])if(r[k]!=null&&(!Array.isArray(r[k])||!r[k].every(Number.isInteger)))throw Error();if(r.trials!=null&&(!Array.isArray(r.trials)||!r.trials.every(t=>typeof t==='string')))throw Error()}}if(!v.profiles.some(p=>p.id===v.active))v.active=v.profiles[0].id;if(!confirm('Ganti profil dan jurnal akun ini dengan cadangan tersebut? Perubahan akan disinkronkan ke perangkat lain.'))return;const old=db;db=v;if(!save()){db=old;return}parent();notify('Cadangan berhasil dipulihkan')}catch{notify('Cadangan tidak valid. Gunakan file ekspor Genius Kids Lab.')}finally{e.target.value=''}}}
async function install(){if(installPrompt){await installPrompt.prompt();installPrompt=null}else notify('Buka menu browser dan pilih Pasang aplikasi atau Tambahkan ke Layar Utama.')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
function route(){if(!ready)return;if(!flushJournal())return;flushJournal=()=>true;hasJournalDraft=()=>false;$$('dialog').forEach(d=>d.close());const page=location.hash.slice(1).split('/')[0]||'home';if(page==='auth-confirm'){renderConfirmation();return}if(['login','register','forgot-password','reset-password'].includes(page)){renderAuthPage(page);return}if(!currentUser()){renderAuthPage('login');return}if(page==='admin'){renderAdmin(shell);return}freshMission=page==='mission';({home,explore,mission,journal,badges,parent}[page]||home)();window.scrollTo(0,0);if(!firstRoute)focusMain();firstRoute=false}
let ready=false;
window.addEventListener('hashchange',route);
try{const res=await fetch('/experiments.json');if(!res.ok)throw Error();exps=await res.json();await initAuth();if(currentUser())await loadAccountData();ready=true;route();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}catch{$('#app').innerHTML='<div class="empty"><span aria-hidden="true">🔌</span><h1>Lab belum dapat dimuat</h1><p>Periksa koneksi, lalu muat ulang halaman.</p><button class="button" onclick="location.reload()">Coba lagi</button></div>'}

function updateSyncStatus(){
  const node=$('#sync-status');if(node){node.textContent=({loading:'◌',syncing:'↻',synced:'✓',pending:'◷',offline:'↥',conflict:'!',error:'!',signedout:'!'})[syncInfo.state]||'◌';node.dataset.state=syncInfo.state;node.title=syncInfo.message;node.setAttribute('aria-label',`Sinkronisasi: ${syncInfo.message}`)}
  const detail=$('#sync-detail');if(detail)detail.textContent=syncInfo.message;
}
function showSync(){
  const dialog=document.createElement('dialog');dialog.className='user-dialog sync-dialog';dialog.setAttribute('aria-labelledby','sync-title');
  const cloud=familySync.conflict,local=familySync.draft||familySync.record.data;
  const summary=data=>`${data?.profiles?.length||0} profil · ${(data?.profiles||[]).reduce((n,p)=>n+Object.values(p.entries).filter(e=>e.observation).length,0)} jurnal`;
  dialog.innerHTML=`<div class="panel-head"><h2 id="sync-title">Sinkronisasi akun</h2><button type="button" class="small ghost" data-close aria-label="Tutup">✕</button></div><p id="sync-detail" role="status">${esc(syncInfo.message)}</p>${syncInfo.updatedAt?`<p class="muted">Terakhir tersimpan: ${new Date(syncInfo.updatedAt).toLocaleString('id-ID')}</p>`:''}${cloud?`<div class="sync-versions"><div><b>Versi perangkat ini</b><p>${summary(local)}</p></div><div><b>Versi ${cloud.source==='tab'?'tab lain':'akun'}</b><p>${summary(cloud.data)}</p></div></div><p>Unduh kedua cadangan sebelum memilih. Versi yang dipilih akan mengganti seluruh profil, progres, dan jurnal.</p><div class="form-actions"><button class="button secondary" id="backup-local">Unduh versi perangkat</button><button class="button secondary" id="backup-remote">Unduh versi lain</button></div><div class="form-actions"><button class="button" data-resolve="remote">Gunakan versi ${cloud.source==='tab'?'tab lain':'akun'}</button><button class="button secondary" data-resolve="local">Gunakan versi perangkat ini</button></div>`:`<p>Perubahan disimpan di perangkat terlebih dahulu, lalu dikirim secara privat ke akun Anda. Profil, checklist, jurnal, dan foto ikut tersinkron. Maksimal 3 MB per akun.</p>${syncInfo.state==='signedout'?'<a class="button" href="#login">Masuk kembali</a>':''}<div class="form-actions"><button class="button" id="sync-now">Sinkronkan sekarang</button><button class="button secondary" id="backup-local">Unduh cadangan</button></div>`}`;
  document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-close]').onclick=()=>dialog.close();
  dialog.querySelector('#backup-local').onclick=()=>download(`genius-kids-perangkat-${Date.now()}.json`,local);
  if(cloud){dialog.querySelector('#backup-remote').onclick=()=>download(`genius-kids-versi-lain-${Date.now()}.json`,cloud.data);dialog.querySelectorAll('[data-resolve]').forEach(button=>button.onclick=async()=>{
    if(!confirm('Ganti data dengan versi yang dipilih? Unduh cadangan terlebih dahulu jika ingin menyimpan kedua versi.'))return;
    button.disabled=true;flushJournal=()=>true;await familySync.resolve(button.dataset.resolve);dialog.close();route();if(familySync.conflict)showSync();
  })}else dialog.querySelector('#sync-now').onclick=async()=>{if(!flushJournal())return;const button=dialog.querySelector('#sync-now');button.disabled=true;await familySync.refresh();button.disabled=false;if(familySync.conflict){dialog.close();showSync()}};
  dialog.showModal();
}
async function refreshFamily(){if(!familySync||currentUser()?.id!==familySync.userId)return;if(document.activeElement?.matches('input,textarea,select'))return;if(flushJournal())await familySync.refresh()}
window.addEventListener('online',refreshFamily);
window.addEventListener('focus',refreshFamily);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refreshFamily();else flushJournal()});
window.addEventListener('storage',event=>{if(event.key===familySync?.key)familySync.externalChange()});
window.addEventListener('beforeunload',event=>{if(!flushJournal()||familySync?.conflict){event.preventDefault();event.returnValue=''}});
setInterval(()=>{if(document.visibilityState==='visible')refreshFamily()},30000);
