import { test, expect } from '@playwright/test';

test('register, local journal, logout, reset via email, login, and admin denial', async ({ page, request }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true });
  await page.getByRole('link', { name: 'Daftar sekarang' }).click();
  await page.getByLabel('Nama orang tua').fill('Keluarga Browser');
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-family-password');
  await page.getByLabel('Konfirmasi password').fill('different-password');
  await page.getByRole('button', { name: 'Buat akun' }).click();
  await expect(page.getByRole('alert')).toContainText('Konfirmasi password belum cocok');
  await page.getByLabel('Konfirmasi password').fill('browser-family-password');
  await page.getByRole('button', { name: 'Buat akun' }).click();
  await confirmSignup(page, request, 'browser@example.test');
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#admin');
  await expect(page.getByRole('heading', { name: 'Akses terbatas' })).toBeVisible();
  await page.goto('/#mission/1');
  await page.getByLabel('Kami sudah membaca petunjuk keamanan bersama.').check();
  await page.getByRole('button', { name: 'Siap, mulai misi' }).click();
  await page.getByRole('tab', { name: /Catat/ }).click();
  await page.getByLabel('Apa yang kamu lihat?').fill('Air berubah selama percobaan.');
  await page.getByRole('button', { name: 'Simpan jurnal', exact: true }).click();
  await page.goto('/#journal');
  await expect(page.getByText('Air berubah selama percobaan.', { exact: true })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.getByRole('link', { name: 'Daftar sekarang' }).click();
  await page.getByLabel('Nama orang tua').fill('Keluarga Kedua');
  await page.getByLabel('Alamat email').fill('second@example.test');
  await page.getByLabel('Password', { exact: true }).fill('second-family-password');
  await page.getByLabel('Konfirmasi password').fill('second-family-password');
  await page.getByRole('button', { name: 'Buat akun' }).click();
  await confirmSignup(page, request, 'second@example.test');
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#journal');
  await expect(page.getByRole('heading', { name: 'Halaman pertama menantimu' })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.getByRole('link', { name: 'Lupa password?' }).click();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.locator('.form-message.success')).toContainText('Jika email terdaftar');
  const outbox = await (await request.get('/api/test-outbox')).json();
  await page.goto(outbox.at(-1).url);
  await page.getByRole('button', { name: 'Lanjutkan reset password' }).click();
  await page.getByLabel('Password baru', { exact: true }).fill('browser-family-new-password');
  await page.getByLabel('Konfirmasi password').fill('browser-family-new-password');
  await page.getByRole('button', { name: 'Simpan password baru' }).click();
  await expect(page.locator('.form-message.success')).toContainText('Password diperbarui');
  await page.getByRole('link', { name: 'Kembali ke login' }).click();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-family-new-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#journal');
  await expect(page.getByText('Air berubah selama percobaan.', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('admin creates, searches, edits, disables and deletes a user', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/#login');
  await page.getByLabel('Alamat email').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-admin-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.getByRole('link', { name: 'Admin', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'Admin Uji (Anda)' })).toBeVisible();
  await page.getByRole('button', { name: 'Tambah pengguna' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nama', { exact: true }).fill('Managed Family');
  await dialog.getByLabel('Email', { exact: true }).fill('managed@example.test');
  await dialog.getByLabel('Password awal').fill('managed-family-password');
  await dialog.getByRole('button', { name: 'Buat pengguna' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('cell', { name: 'Managed Family managed@example.test', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('button', { name: 'Tambah pengguna' })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByLabel('Cari nama atau email pengguna').fill('managed');
  await page.getByRole('button', { name: 'Cari', exact: true }).click();
  await expect(page.getByRole('row')).toHaveCount(2);
  await page.getByRole('button', { name: 'Edit Managed Family' }).click();
  await dialog.getByLabel('Nama', { exact: true }).fill('Updated Family');
  await dialog.getByLabel('Akun aktif').uncheck();
  await dialog.getByRole('button', { name: 'Simpan perubahan' }).click();
  await expect(page.getByText('Nonaktif', { exact: true })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Hapus Updated Family' }).click();
  await expect(page.getByRole('heading', { name: 'Pengguna tidak ditemukan' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile login fits viewport and has working register navigation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#login');
  await expect(page.getByRole('button', { name: 'Masuk ke lab' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/login-mobile.png', fullPage: true });
  await page.getByRole('link', { name: 'Daftar sekarang' }).click();
  await expect(page.getByLabel('Nama orang tua')).toBeVisible();
});

async function confirmSignup(page, request, email) {
  await expect(page.locator('.form-message.success')).toContainText('Periksa email');
  const outbox = await (await request.get('/api/test-outbox')).json();
  const confirmation = outbox.findLast(mail => mail.email === email && mail.type === 'email');
  await page.goto(confirmation.url);
  await page.getByRole('button', { name: 'Konfirmasi email', exact: true }).click();
}
