import { test, expect } from '@playwright/test';

test('managed account login, local journal, logout, reset via email, login, and admin denial', async ({ page, request }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true });
  await expect(page.getByRole('link', { name: 'Daftar akun' })).toBeVisible();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-family-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#admin');
  await expect(page.getByRole('heading', { name: 'Akses terbatas' })).toBeVisible();
  await page.goto('/#mission/1');
  await page.getByLabel('Kami sudah membaca petunjuk keamanan bersama.').check();
  await page.getByRole('button', { name: 'Siap, mulai misi' }).click();
  await page.getByRole('tab', { name: /Catat/ }).click();
  await page.getByLabel('Apa yang kamu lihat?').fill('Air berubah selama percobaan.');
  await page.getByRole('button', { name: 'Simpan jurnal', exact: true }).click();
  await page.goto('/#journal');
  await expect(page.getByText('Air berubah selama percobaan.', { exact: true })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.getByLabel('Alamat email').fill('second@example.test');
  await page.getByLabel('Password', { exact: true }).fill('second-family-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#journal');
  await expect(page.getByRole('heading', { name: 'Halaman pertama menantimu' })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.getByRole('link', { name: 'Lupa password?' }).click();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.locator('.form-message.success')).toContainText('Jika email terdaftar');
  const outbox = await (await request.get('/api/test-outbox')).json();
  await page.goto(outbox.at(-1).url);
  await page.getByRole('button', { name: 'Lanjutkan reset password' }).click();
  await page.getByLabel('Password baru', { exact: true }).fill('browser-family-new-password');
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('browser-family-new-password');
  await page.getByRole('button', { name: 'Simpan password baru' }).click();
  await expect(page.locator('.form-message.success')).toContainText('Password diperbarui');
  await page.getByRole('link', { name: 'Kembali ke login' }).click();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-family-new-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#journal');
  await expect(page.getByText('Air berubah selama percobaan.', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('admin creates, searches, edits, disables and deletes a user', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/#login');
  await page.getByLabel('Alamat email').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-admin-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.getByRole('link', { name: 'Admin', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'Admin Uji (Anda)' })).toBeVisible();
  await page.getByRole('button', { name: 'Tambah pengguna' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nama', { exact: true }).fill('Managed Family');
  await dialog.getByLabel('Email', { exact: true }).fill('managed@example.test');
  await dialog.getByLabel('Password awal', { exact: true }).fill('managed-family-password');
  await dialog.getByLabel('Konfirmasi password', { exact: true }).fill('different-password');
  await dialog.getByRole('button', { name: 'Buat pengguna' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Konfirmasi password belum cocok');
  await dialog.getByLabel('Konfirmasi password', { exact: true }).fill('managed-family-password');
  await dialog.getByRole('button', { name: 'Tampilkan password awal', exact: true }).click();
  await expect(dialog.getByLabel('Password awal', { exact: true })).toHaveAttribute('type','text');
  await dialog.getByRole('button', { name: 'Buat pengguna' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('cell', { name: 'Managed Family managed@example.test', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('button', { name: 'Tambah pengguna' })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByLabel('Cari nama atau email pengguna').fill('managed');
  await page.getByRole('button', { name: 'Cari', exact: true }).click();
  await expect(page.getByRole('row')).toHaveCount(2);
  await page.getByRole('button', { name: 'Edit Managed Family' }).click();
  await dialog.getByLabel('Nama', { exact: true }).fill('Updated Family');
  await dialog.getByLabel('Akun aktif').uncheck();
  await dialog.getByRole('button', { name: 'Simpan perubahan' }).click();
  await expect(page.locator('.users-table').getByText('Nonaktif', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Hapus Updated Family' }).click();
  await expect(dialog.getByRole('button', { name: 'Hapus permanen' })).toBeDisabled();
  await dialog.getByLabel('Ketik email pengguna').fill('wrong@example.test');
  await expect(dialog.getByRole('button', { name: 'Hapus permanen' })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Batal', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Hapus Updated Family' })).toBeVisible();
  await page.getByRole('button', { name: 'Hapus Updated Family' }).click();
  await dialog.getByLabel('Ketik email pengguna').fill('managed@example.test');
  await dialog.getByRole('button', { name: 'Hapus permanen' }).click();
  await expect(page.locator('#admin-message')).toContainText('berhasil dihapus');
  await expect(page.getByRole('heading', { name: 'Pengguna tidak ditemukan' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile self-registration validates fields and creates an immediately usable account', async ({ page, request }) => {
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#login');
  await page.getByRole('link', { name: 'Daftar akun' }).click();
  await expect(page).toHaveURL(/#register$/);
  await expect(page.getByRole('heading', { name: 'Buat akun orang tua' })).toBeVisible();
  await page.reload();
  await page.getByLabel('Nama orang tua').fill('Keluarga Mandiri');
  await page.getByLabel('Alamat email').fill('self-ui@example.test');
  await page.getByLabel('Password', { exact: true }).fill('self-service-password');
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('different-password');
  await page.getByRole('button', { name: 'Daftar akun' }).click();
  await expect(page.getByRole('alert')).toContainText('Konfirmasi password belum cocok');
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('self-service-password');
  await page.route('**/api/auth/register', route=>route.abort(), {times:1});
  await page.getByRole('button', { name: 'Daftar akun' }).click();
  await expect(page.getByRole('alert')).toContainText('Periksa koneksi internet');
  await expect(page.getByLabel('Nama orang tua')).toHaveValue('Keluarga Mandiri');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/register-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Daftar akun' }).click();
  await expect(page).toHaveURL(/#login$/);
  await expect(page.locator('.form-message.success')).toContainText('langsung aktif');
  await expect(page.getByLabel('Alamat email')).toHaveValue('self-ui@example.test');
  await expect(page.getByLabel('Password', { exact: true })).toBeEmpty();
  const outbox=await (await request.get('/api/test-outbox')).json();
  expect(outbox.filter(mail=>mail.email==='self-ui@example.test')).toHaveLength(0);
  await page.getByLabel('Password', { exact: true }).fill('self-service-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#admin');
  await expect(page.getByRole('heading', { name: 'Akses terbatas' })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await page.getByRole('link', { name: 'Daftar akun' }).click();
  await page.getByLabel('Nama orang tua').fill('Duplicate');
  await page.getByLabel('Alamat email').fill('self-ui@example.test');
  await page.getByLabel('Password', { exact: true }).fill('self-service-password');
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('self-service-password');
  await page.getByRole('button', { name: 'Daftar akun' }).click();
  await expect(page.getByRole('alert')).toContainText('Email sudah digunakan');
  await expect(page.getByRole('button', { name: 'Daftar akun' })).toBeEnabled();
  expect(errors).toEqual([]);
});

test('password guidance, visibility and Caps Lock work without submitting login', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto('/#login');
  const password = page.getByLabel('Password', { exact: true });
  await expect(password).toHaveAccessibleDescription(/membedakan huruf besar dan kecil/);
  await password.fill('a-password-to-check');
  await page.getByRole('button', { name: 'Tampilkan password', exact: true }).click();
  await expect(password).toHaveAttribute('type', 'text');
  await expect(page.getByRole('button', { name: 'Sembunyikan password', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(password).toHaveValue('a-password-to-check');
  await page.getByRole('button', { name: 'Sembunyikan password', exact: true }).click();
  await expect(password).toHaveAttribute('type', 'password');
  await password.focus();
  await password.dispatchEvent('keydown', { key: 'A', modifierCapsLock: true });
  await expect(page.getByText('Caps Lock aktif.')).toBeVisible();
  await password.dispatchEvent('keyup', { key: 'CapsLock', modifierCapsLock: false });
  await expect(page.getByText('Caps Lock aktif.')).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/password-hints-mobile.png', fullPage: true });
  await page.goto('/#reset-password');
  await expect(page.getByLabel('Password baru', { exact: true })).toHaveAccessibleDescription(/12–128 karakter/);
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('confirm-password');
  await page.getByRole('button', { name: 'Tampilkan konfirmasi password', exact: true }).click();
  await expect(page.getByLabel('Konfirmasi password', { exact: true })).toHaveAttribute('type', 'text');
  await expect(page.getByLabel('Password baru', { exact: true })).toHaveAttribute('type', 'password');
});

test('forgot password carries email from failed login and supports retry after a network error', async ({ page }) => {
  await page.goto('/#login');
  await page.getByLabel('Alamat email').fill('recovery-ui@example.test');
  await page.getByLabel('Password', { exact: true }).fill('incorrect-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('alert')).toContainText('Email atau password salah');
  await page.getByRole('link', { name: 'Lupa password?' }).click();
  await expect(page.getByLabel('Alamat email')).toHaveValue('recovery-ui@example.test');
  await expect(page.locator('input[name="password"]')).toHaveCount(0);
  await page.route('**/api/auth/forgot-password', route => route.abort(), { times: 1 });
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.getByRole('alert')).toContainText('Periksa koneksi internet');
  await expect(page.getByRole('button', { name: 'Kirim tautan reset' })).toBeEnabled();
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.locator('#auth-form').getByRole('status')).toContainText('Jika email terdaftar');
  await expect(page.getByText('Langkah berikutnya', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Kirim ulang tautan' }).click();
  await expect(page.locator('#auth-form').getByRole('status')).toContainText('Jika email terdaftar');
  await page.screenshot({ path: 'test-results/forgot-password-success.png', fullPage: true });
  await page.getByLabel('Alamat email').fill('another@example.test');
  await expect(page.getByText('Langkah berikutnya', { exact: true })).toBeHidden();
  await expect(page.getByRole('button', { name: 'Kirim tautan reset' })).toBeVisible();
});

test('admin filters, refresh retry, protected account and duplicate email feedback', async ({ page }) => {
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  await page.goto('/#login');
  await page.getByLabel('Alamat email').fill('admin@example.test');
  await page.getByLabel('Password', {exact:true}).fill('browser-admin-password');
  await page.getByRole('button',{name:'Masuk ke lab'}).click();
  await page.getByRole('link',{name:'Admin',exact:true}).click();
  await expect(page.getByRole('cell',{name:'Admin Uji (Anda)'})).toBeVisible();
  await page.getByLabel('Filter peran').selectOption('admin');
  await expect(page.getByRole('row')).toHaveCount(2);
  await expect(page.getByRole('button',{name:'Hapus Admin Uji'})).toBeDisabled();
  await page.getByRole('button',{name:'Edit Admin Uji'}).click();
  const dialog=page.getByRole('dialog');
  await expect(dialog.getByLabel('Peran',{exact:true})).toBeDisabled();
  await expect(dialog.getByLabel('Akun aktif')).toBeDisabled();
  await dialog.getByRole('button',{name:'Batal',exact:true}).click();
  await page.getByRole('button',{name:'Reset filter'}).click();
  await expect(page.getByRole('cell',{name:'Dormant Family dormant@example.test',exact:true})).toBeVisible();
  await page.getByLabel('Filter status').selectOption('inactive');
  await expect(page.getByRole('row')).toHaveCount(2);
  await expect(page.getByRole('cell',{name:'Dormant Family dormant@example.test',exact:true})).toBeVisible();
  await page.route('**/api/admin/users?**',route=>route.abort(),{times:1});
  await page.getByRole('button',{name:'Muat ulang'}).click();
  await expect(page.getByRole('heading',{name:'Data belum dapat dimuat'})).toBeVisible();
  await page.getByRole('button',{name:'Coba lagi',exact:true}).click();
  await expect(page.getByRole('cell',{name:'Dormant Family dormant@example.test',exact:true})).toBeVisible();
  await expect(page.getByLabel('Filter status')).toHaveValue('inactive');
  await page.getByRole('button',{name:'Reset filter'}).click();
  await page.getByLabel('Urutkan pengguna').selectOption('name');
  await expect(page.locator('.users-table tbody tr').first()).toContainText('Admin Uji');
  await expect(page.getByRole('button',{name:'Berikutnya'})).toBeDisabled();
  await page.screenshot({path:'test-results/admin-enhanced-desktop.png',fullPage:true});
  await page.setViewportSize({width:360,height:800});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByLabel('Filter peran')).toBeVisible();
  await page.screenshot({path:'test-results/admin-enhanced-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Tambah pengguna'}).click();
  await dialog.getByLabel('Nama',{exact:true}).fill('Duplicate');
  await dialog.getByLabel('Email',{exact:true}).fill('admin@example.test');
  await dialog.getByLabel('Password awal',{exact:true}).fill('duplicate-password-123');
  await dialog.getByLabel('Konfirmasi password',{exact:true}).fill('duplicate-password-123');
  await dialog.getByRole('button',{name:'Buat pengguna'}).click();
  await expect(dialog.getByRole('alert')).toContainText('Email sudah digunakan');
  await expect(dialog.getByLabel('Nama',{exact:true})).toHaveValue('Duplicate');
  await expect(dialog.getByRole('button',{name:'Buat pengguna'})).toBeEnabled();
  await dialog.getByRole('button',{name:'Batal',exact:true}).click();
  expect(errors).toEqual([]);
});
