import { test, expect } from '@playwright/test';

test('managed account login, local journal, logout, reset via email, login, and admin denial', async ({ page, request }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.screenshot({ path: 'test-results/login-desktop.png', fullPage: true });
  await expect(page.getByRole('link', { name: 'Daftar sekarang' })).toHaveCount(0);
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-family-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#admin');
  await expect(page.getByRole('heading', { name: 'Akses terbatas' })).toBeVisible();
  await page.goto('/#mission/1');
  await page.getByLabel('Kami sudah membaca petunjuk keamanan bersama.').check();
  await page.getByRole('button', { name: 'Siap, mulai misi' }).click();
  await page.getByRole('tab', { name: /Catat/ }).click();
  await page.getByLabel('Apa yang kamu lihat?').fill('Air berubah selama percobaan.');
  await page.getByRole('button', { name: 'Simpan jurnal', exact: true }).click();
  await page.goto('/#journal');
  await expect(page.getByText('Air berubah selama percobaan.', { exact: true })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.getByLabel('Alamat email').fill('second@example.test');
  await page.getByLabel('Password', { exact: true }).fill('second-family-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#journal');
  await expect(page.getByRole('heading', { name: 'Halaman pertama menantimu' })).toBeVisible();
  await page.goto('/#parent');
  await page.getByRole('button', { name: 'Keluar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Selamat datang kembali' })).toBeVisible();
  await page.getByRole('link', { name: 'Lupa password?' }).click();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.locator('.form-message.success')).toContainText('Jika email terdaftar');
  const outbox = await (await request.get('/api/test-outbox')).json();
  await page.goto(outbox.at(-1).url);
  await page.getByRole('button', { name: 'Lanjutkan reset password' }).click();
  await page.getByLabel('Password baru', { exact: true }).fill('browser-family-new-password');
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('browser-family-new-password');
  await page.getByRole('button', { name: 'Simpan password baru' }).click();
  await expect(page.locator('.form-message.success')).toContainText('Password diperbarui');
  await page.getByRole('link', { name: 'Kembali ke login' }).click();
  await page.getByLabel('Alamat email').fill('browser@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-family-new-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.goto('/#journal');
  await expect(page.getByText('Air berubah selama percobaan.', { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});

test('admin creates, searches, edits, disables and deletes a user', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/#login');
  await page.getByLabel('Alamat email').fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-admin-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('heading', { name: 'Halo, Ilmuwan Cilik!' })).toBeVisible();
  await page.getByRole('link', { name: 'Admin', exact: true }).click();
  await expect(page.getByRole('cell', { name: 'Admin Uji (Anda)' })).toBeVisible();
  await page.getByRole('button', { name: 'Tambah pengguna' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Nama', { exact: true }).fill('Managed Family');
  await dialog.getByLabel('Email', { exact: true }).fill('managed@example.test');
  await dialog.getByLabel('Password awal').fill('managed-family-password');
  await dialog.getByRole('button', { name: 'Buat pengguna' }).click();
  await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('cell', { name: 'Managed Family managed@example.test', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 360, height: 800 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('button', { name: 'Tambah pengguna' })).toBeVisible();
  await page.screenshot({ path: 'test-results/admin-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByLabel('Cari nama atau email pengguna').fill('managed');
  await page.getByRole('button', { name: 'Cari', exact: true }).click();
  await expect(page.getByRole('row')).toHaveCount(2);
  await page.getByRole('button', { name: 'Edit Managed Family' }).click();
  await dialog.getByLabel('Nama', { exact: true }).fill('Updated Family');
  await dialog.getByLabel('Akun aktif').uncheck();
  await dialog.getByRole('button', { name: 'Simpan perubahan' }).click();
  await expect(page.getByText('Nonaktif', { exact: true })).toBeVisible();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Hapus Updated Family' }).click();
  await expect(page.getByRole('heading', { name: 'Pengguna tidak ditemukan' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile login fits viewport and old registration links show admin guidance', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/#login');
  await expect(page.getByRole('button', { name: 'Masuk ke lab' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/login-mobile.png', fullPage: true });
  await page.goto('/#register');
  await expect(page).toHaveURL(/#login$/);
  await expect(page.getByText('Belum punya akun? Hubungi administrator untuk pendaftaran.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Buat akun' })).toHaveCount(0);
});

test('password guidance, visibility and Caps Lock work without submitting login', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 800 });
  await page.goto('/#login');
  const password = page.getByLabel('Password', { exact: true });
  await expect(password).toHaveAccessibleDescription(/membedakan huruf besar dan kecil/);
  await password.fill('a-password-to-check');
  await page.getByRole('button', { name: 'Tampilkan password', exact: true }).click();
  await expect(password).toHaveAttribute('type', 'text');
  await expect(page.getByRole('button', { name: 'Sembunyikan password', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(password).toHaveValue('a-password-to-check');
  await page.getByRole('button', { name: 'Sembunyikan password', exact: true }).click();
  await expect(password).toHaveAttribute('type', 'password');
  await password.focus();
  await password.dispatchEvent('keydown', { key: 'A', modifierCapsLock: true });
  await expect(page.getByText('Caps Lock aktif.')).toBeVisible();
  await password.dispatchEvent('keyup', { key: 'CapsLock', modifierCapsLock: false });
  await expect(page.getByText('Caps Lock aktif.')).toBeHidden();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/password-hints-mobile.png', fullPage: true });
  await page.goto('/#reset-password');
  await expect(page.getByLabel('Password baru', { exact: true })).toHaveAccessibleDescription(/12–128 karakter/);
  await page.getByLabel('Konfirmasi password', { exact: true }).fill('confirm-password');
  await page.getByRole('button', { name: 'Tampilkan konfirmasi password', exact: true }).click();
  await expect(page.getByLabel('Konfirmasi password', { exact: true })).toHaveAttribute('type', 'text');
  await expect(page.getByLabel('Password baru', { exact: true })).toHaveAttribute('type', 'password');
});

test('forgot password carries email from failed login and supports retry after a network error', async ({ page }) => {
  await page.goto('/#login');
  await page.getByLabel('Alamat email').fill('recovery-ui@example.test');
  await page.getByLabel('Password', { exact: true }).fill('incorrect-password');
  await page.getByRole('button', { name: 'Masuk ke lab' }).click();
  await expect(page.getByRole('alert')).toContainText('Email atau password salah');
  await page.getByRole('link', { name: 'Lupa password?' }).click();
  await expect(page.getByLabel('Alamat email')).toHaveValue('recovery-ui@example.test');
  await expect(page.locator('input[name="password"]')).toHaveCount(0);
  await page.route('**/api/auth/forgot-password', route => route.abort(), { times: 1 });
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.getByRole('alert')).toContainText('Periksa koneksi internet');
  await expect(page.getByRole('button', { name: 'Kirim tautan reset' })).toBeEnabled();
  await page.getByRole('button', { name: 'Kirim tautan reset' }).click();
  await expect(page.locator('#auth-form').getByRole('status')).toContainText('Jika email terdaftar');
  await expect(page.getByText('Langkah berikutnya', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Kirim ulang tautan' }).click();
  await expect(page.locator('#auth-form').getByRole('status')).toContainText('Jika email terdaftar');
  await page.screenshot({ path: 'test-results/forgot-password-success.png', fullPage: true });
  await page.getByLabel('Alamat email').fill('another@example.test');
  await expect(page.getByText('Langkah berikutnya', { exact: true })).toBeHidden();
  await expect(page.getByRole('button', { name: 'Kirim tautan reset' })).toBeVisible();
});
